[workspace]
members = [
    "kiro-audio",
    "kiro-midi",
    "kiro-engine",
    "kiro-studio",
#    "kiro-synth",
#    "kiro-synth-dsp",
]

exclude = [
    "incubator",
    "kiro-synth",
    "kiro-synth-dsp"
]

[profile.dev]
split-debuginfo = "unpacked"
